import crypto from 'crypto';

/**
 * Verify ECDSA Signature (Server-Side)
 * 
 * Purpose:
 * - Verify signatures generated by the client's Web Crypto API
 * - Uses Node.js 'crypto' module
 * 
 * @param {Object} jwk - The public key in JWK format
 * @param {string} data - The data that was signed (string)
 * @param {string} signatureBase64 - The signature in Base64 format
 * @returns {boolean} True if signature is valid
 */
export const verifySignature = (jwk, data, signatureBase64) => {
    try {
        // 1. Import the public key from JWK
        const publicKey = crypto.createPublicKey({
            key: jwk,
            format: 'jwk'
        });

        // 2. Decode signature from Base64
        const signature = Buffer.from(signatureBase64, 'base64');

        // 3. Verify using SHA-256
        const verify = crypto.createVerify('SHA256');
        verify.update(data);
        verify.end();

        // Web Crypto API produces raw signatures (IEEE P1363)
        // Node.js defaults to DER, so we must specify the encoding
        return verify.verify({
            key: publicKey,
            dsaEncoding: 'ieee-p1363'
        }, signature);
    } catch (error) {
        console.error('Server-side signature verification failed:', error);
        return false;
    }
};

/**
 * Canonicalize an object for signing
 * 
 * Sorts keys recursively to ensure deterministic serialization.
 * 
 * @param {Object} obj 
 * @returns {string} Canonical JSON string
 */
const canonicalize = (obj) => {
    if (obj === null || typeof obj !== 'object' || Array.isArray(obj)) {
        return JSON.stringify(obj);
    }

    const keys = Object.keys(obj).sort();
    const result = {};
    for (const key of keys) {
        result[key] = obj[key];
    }
    return JSON.stringify(result);
};

/**
 * Verify Object Signature
 * 
 * Purpose:
 * - Verify signature of a JSON object
 * - Must match the serialization used on the client (JSON.stringify)
 * 
 * @param {Object} jwk - Public key in JWK format
 * @param {Object} obj - The object to verify
 * @param {string} signatureBase64 - Base64 signature
 * @returns {boolean}
 */
export const verifyObjectSignature = (jwk, obj, signatureBase64) => {
    try {
        // Use canonical serialization to match client
        const jsonString = canonicalize(obj);
        console.log('Server verifying payload:', jsonString); // DEBUG LOG
        return verifySignature(jwk, jsonString, signatureBase64);
    } catch (error) {
        console.error('Object verification failed:', error);
        return false;
    }
};
